name: 🌐 开启web配置网站

on:
  push:
    branches: [ main, master ]
    paths:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: 发布页面
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 配置 GitHub Pages
        uses: actions/configure-pages@v5

      - name: 上传 docs 目录
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
